keys:
  - &user age167vnfruu6y7efllkfx2gytnd8c2c2kx4lzc79kghcrjtf5652sdsle68ml
  - &illusion age19p6nk5c26f9rvx9ndw9nc7jhn0gh5jqlxyk0c20jgtchwk95cy0qzxux6a
creation_rules:
  - path_regex: lib/secrets.yaml$
    key_groups:
    - age:
      - *user
      - *illusion
