keys:
  - &user age167vnfruu6y7efllkfx2gytnd8c2c2kx4lzc79kghcrjtf5652sdsle68ml
  - &illusion age1k6fdu4nq2tjrwywjl0wtjqrzrl3jze9tgy4cpmwzp3an0lhzjprseqqfgt
creation_rules:
  - path_regex: lib/secrets.yaml$
    key_groups:
    - age:
      - *user
      - *illusion
