keys:
  - &user age167vnfruu6y7efllkfx2gytnd8c2c2kx4lzc79kghcrjtf5652sdsle68ml
  - &illusion age1r9u2fds2q2xflf3pdqrw0vs8j78df8yyj5vvt47yuwwlxe4f6swqnmyynn
creation_rules:
  - path_regex: lib/secrets.yaml$
    key_groups:
    - age:
      - *user
      - *illusion
