keys:
  - &users
    - &mxxntype age167vnfruu6y7efllkfx2gytnd8c2c2kx4lzc79kghcrjtf5652sdsle68ml
  - &hosts
    - &Nox age132vf5d6z20ajf86pn3zenhwfy78ql5eyqaff92n04u6gdd0eg5wqtlrxjx
    - &Wyrm age1ukjfmfhz8jjh9yf7tk390nk7vje2ltw2a9urm39d27a5cnngje5svaksur
    - &Luna age1nrcz6pt8ggx2lpmqpsv70shqfdlwgyc8sxxyckvd3emw9ur6kc0q0tc6nu
creation_rules:
  - path_regex: lib/secrets.ya?ml$
    key_groups:
    - age:
      - *mxxntype
      - *Nox
      - *Wyrm
      - *Luna
