[placeholders.nix]
type = "bool"
prompt = "Set up a Nix flake?"
default = true

[conditional.'crate_type == "bin"']
ignore = [
    "src/lib.rs",
    "Cargo.lock"
]

[conditional.'crate_type == "lib"']
ignore = [
    "src/main.rs",
]

[conditional.'nix == false']
ignore = [
    "flake.nix",
    "flake.lock",
]
