[template]
ignore = [
    "flake.lock",
    "Cargo.lock",
]

[placeholders.nix]
type = "bool"
prompt = "Set up a Nix flake?"
default = true

[placeholders.description]
type = "string"
prompt = "Provide a description"

[conditional.'crate_type == "bin"']
ignore = [
    "src/lib.rs",
]

[conditional.'crate_type == "lib"']
ignore = [
    "src/main.rs",
    "Cargo.lock"
]

[conditional.'nix == false']
ignore = [
    "shells",
    "packages",
    "flake.nix",
    "flake.lock",
]
