name: Typos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: typos-action
        uses: crate-ci/typos@v1.17.2
            
